// Pitch — rebuilt around the MAP push. One pitch per outlet, created from plan initiatives pushed to the outlet's
// sales officer (by the priority rule, or confirmed by the ASM), or from a Thermometer recommendation routed to
// Pitch. Outlets, KPIs and talking points come from each outlet's own workbook rows (GET /api/web/bootstrap →
// `pitch`); a pitch counts as visited when the officer's last recorded visit is on or after the plan date.

import { ActionTrace } from "./actionTraces";
import { AgentId } from "./cortexHome";
import { Initiative, MAP_LABELS, Priority, SEP_INITIATIVES, SEP_PLAN, Territory, execFor } from "./map";
import { D } from "./source";

const P = <T,>(key: string) => D<T>("pitch", key);

export type OutletType = "Distributor" | "Dealer" | "Retailer";

export const OUTLETS = P<Record<string, { type: OutletType; territory: Territory; code: string }>>("OUTLETS");

/** Outlets each not-yet-pushed initiative would reach, if the ASM confirms the suggestion. */
export const SUGGESTED_OUTLETS = P<Record<string, string[]>>("SUGGESTED_OUTLETS");

export type PitchSource =
  | { kind: "plan"; initiative: string; mode: "auto" | "confirmed" }
  | { kind: "thermometer"; rec: string; label: string };

export type PitchStatus = "queued" | "in-sfa" | "visited";
export const PITCH_STATUS: Record<PitchStatus, { label: string; color: string }> = {
  queued: { label: "Not generated", color: "#7c7f89" },
  "in-sfa": { label: "In SFA", color: "#4f86f7" },
  visited: { label: "Visited", color: "#2fa85c" },
};

export interface SfaEvent {
  by: string;
  at: string;
  when: string;
  note?: string;
}

export interface TalkingPoint {
  n: number;
  topic: string;
  point: string;
  why: string;
  logic: string;
  evidence: string;
  conf: number | null;
  /** the plan initiative this point carries, when it came from a push */
  fromPlan?: number;
  covered?: SfaEvent;
}

export interface Pitch {
  id: string;
  outlet: string;
  type: OutletType;
  territory: Territory;
  code: string;
  se: string;
  sources: PitchSource[];
  status: PitchStatus;
  generated?: string;
  sfaAt?: string;
  visited?: SfaEvent;
  language: string;
  tone: string;
  /** something arrived after generation (the "What's new" banner) */
  news?: { agent: AgentId; when: string; text: string }[];
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-");

/** Officers' last recorded visits on or after the plan date, per outlet. */
const STATE = P<Record<string, { visited: SfaEvent }>>("STATE");
const THERMO_ROUTE = P<{ outlet: string; rec: string; label: string; point: Omit<TalkingPoint, "n"> } | null>("THERMO_ROUTE");
const KPIS = P<Record<string, { value: string; target: string; outstanding: string; skus: string }>>("KPIS");
const POINTS = P<Record<string, Omit<TalkingPoint, "n">[]>>("POINTS");
const PLAN_LINES = P<Record<string, string>>("PLAN_LINES");
const GENERATED_AT = P<string>("GENERATED_AT");
const LANGUAGE = P<string>("LANGUAGE");

function newPitch(outlet: string, src: PitchSource): Pitch {
  const o = OUTLETS[outlet];
  const st = STATE[outlet];
  return {
    id: `p-${slug(outlet)}`,
    outlet,
    type: o.type,
    territory: o.territory,
    code: o.code,
    se: st?.visited.by ?? execFor(o.territory),
    sources: [src],
    // a plan push generates the pitch and routes it to SFA at once; a visit since then marks it visited
    status: st ? "visited" : "in-sfa",
    generated: GENERATED_AT,
    sfaAt: GENERATED_AT,
    ...(st ? { visited: st.visited } : {}),
    language: LANGUAGE,
    tone: "Balanced",
  };
}

function basePitches(): Pitch[] {
  const byOutlet = new Map<string, Pitch>();
  const add = (outlet: string, src: PitchSource) => {
    if (!OUTLETS[outlet]) return;
    const cur = byOutlet.get(outlet);
    if (cur) cur.sources.push(src);
    else byOutlet.set(outlet, newPitch(outlet, src));
  };
  for (const i of SEP_INITIATIVES) if (i.pitch) for (const o of i.pitch.outlets) add(o, { kind: "plan", initiative: i.id, mode: i.pitch.mode });
  // path 2: an agent recommendation routed to Pitch on its own (homepage / Thermometer done chip)
  if (THERMO_ROUTE) add(THERMO_ROUTE.outlet, { kind: "thermometer", rec: THERMO_ROUTE.rec, label: THERMO_ROUTE.label });
  return Array.from(byOutlet.values());
}

/** Session state shared by Pitch, the pitch detail and the plan table: pushes confirmed, suggestions dismissed, batches created. */
export interface PitchSession {
  pushed: string[];
  dismissed: string[];
  /** pitch ids generated by a Create pitches batch this session */
  created: string[];
}
const KEY = "cx-pitch-session";
export const EMPTY_SESSION: PitchSession = { pushed: [], dismissed: [], created: [] };
export function readSession(): PitchSession {
  try {
    const raw = sessionStorage.getItem(KEY);
    const v = raw ? { ...EMPTY_SESSION, ...JSON.parse(raw) } : EMPTY_SESSION;
    return Array.isArray(v.created) ? v : { ...v, created: [] };
  } catch {
    return EMPTY_SESSION;
  }
}
export function writeSession(s: PitchSession) {
  try {
    sessionStorage.setItem(KEY, JSON.stringify(s));
  } catch {
    /* storage unavailable: state lives for this page only */
  }
}

export const CREATED_AT = "Today, just now";

/** All pitches for this session: the base set, confirmed pushes added (queued until a Create pitches batch). */
export function pitchesFor(s: PitchSession): Pitch[] {
  const list = basePitches();
  for (const id of s.pushed) {
    for (const outlet of SUGGESTED_OUTLETS[id] ?? []) {
      if (!OUTLETS[outlet]) continue;
      const ex = list.find((p) => p.outlet === outlet);
      const src: PitchSource = { kind: "plan", initiative: id, mode: "confirmed" };
      const init = SEP_INITIATIVES.find((x) => x.id === id)!;
      if (ex) {
        ex.sources.push(src);
        if (ex.status !== "queued") ex.news = [...(ex.news ?? []), { agent: "map", when: "Today", text: `${MAP_LABELS.asm} pushed plan initiative #${init.n} (${init.title}) to this pitch. Its talking point is added as a new version.` }];
      } else {
        const p = newPitch(outlet, src);
        list.push({ ...p, status: "queued", generated: undefined, sfaAt: undefined, visited: undefined });
      }
    }
  }
  for (const p of list) if (p.status === "queued" && s.created.includes(p.id)) Object.assign(p, { status: "in-sfa", generated: CREATED_AT, sfaAt: CREATED_AT });
  return list;
}

export function suggestionsFor(s: PitchSession): Initiative[] {
  return SEP_INITIATIVES.filter((i) => !i.pitch && SUGGESTED_OUTLETS[i.id] && !s.pushed.includes(i.id) && !s.dismissed.includes(i.id));
}

// ---------------------------------------------------------------------------
// Talking points — the outlet's own workbook points, with the plan's push carried into the matching topic
// ---------------------------------------------------------------------------

export function kpisFor(p: Pitch) {
  return KPIS[p.outlet] ?? { value: "—", target: "—", outstanding: "—", skus: "—" };
}

function planPoint(i: Initiative): Omit<TalkingPoint, "n"> {
  const topic = i.lever === "Range selling" ? "Sell top seller" : i.lever === "Influencer engagement" || i.lever === "Retail reach" ? "Maintain & grow" : "Open issues";
  return {
    topic,
    point: PLAN_LINES[i.id] ?? i.steps[0],
    why: i.description.split(". ")[0] + ".",
    logic: `Plan initiative #${i.n} · ${i.priority} priority`,
    evidence: `Market Action Plan · ${SEP_PLAN.label.split(" ")[0]} · #${i.n}`,
    conf: i.priority === "High" ? 92 : 81,
    fromPlan: i.n,
  };
}

/** Talking points for one pitch, with the officer's visit applied. */
export function pointsFor(p: Pitch): TalkingPoint[] {
  const base = [...(POINTS[p.outlet] ?? [])];
  // plan pushes become talking points; a Thermometer route becomes the "Open issues" point
  const extra = p.sources.map((s) => (s.kind === "plan" ? planPoint(SEP_INITIATIVES.find((i) => i.id === s.initiative)!) : THERMO_ROUTE!.point));
  const merged = [...base];
  for (const e of extra) {
    const at = merged.findIndex((m) => m.topic === e.topic);
    if (at >= 0 && !merged[at].fromPlan) merged.splice(at, 1, e);
    else merged.splice(Math.min(2, merged.length), 0, e);
  }
  const pts = merged.map((m, i) => ({ ...m, n: i + 1 }));
  // the workbook records the visit, not which points were covered: the plan's own points count as covered
  if (p.status === "visited" && p.visited) for (const t of pts) if (t.fromPlan && t.conf != null) t.covered = { by: p.visited.by, at: p.visited.at, when: p.visited.when };
  return pts;
}

export const outstandingCount = (p: Pitch) => (p.status === "queued" ? 0 : pointsFor(p).filter((t) => t.conf != null && !t.covered).length);

// ---------------------------------------------------------------------------
// Orchestration traces
// ---------------------------------------------------------------------------

export function pitchTrace(p: Pitch): ActionTrace {
  const plan = p.sources.filter((s): s is Extract<PitchSource, { kind: "plan" }> => s.kind === "plan");
  const therm = p.sources.find((s) => s.kind === "thermometer") as Extract<PitchSource, { kind: "thermometer" }> | undefined;
  const auto = plan.some((s) => s.mode === "auto");
  const first = plan[0] && SEP_INITIATIVES.find((i) => i.id === plan[0].initiative)!;
  const month = SEP_PLAN.label.split(" ")[0];
  return {
    input: therm
      ? { label: therm.label, detail: `${p.outlet} · ${p.territory}`, at: p.generated ?? "Queued" }
      : { label: auto ? `${month} plan agreed · auto-push` : `Pushed by ${MAP_LABELS.asm} from the plan`, detail: `#${first?.n} ${first?.title} · ${first?.priority} priority`, at: p.generated ?? "Queued" },
    evaluated: [
      ...(therm ? [{ agent: "thermometer" as AgentId, verdict: "routed the recommendation to Pitch on its own", chosen: true }] : [{ agent: "map" as AgentId, verdict: auto ? "pushed it under the High-priority rule" : `held it below the auto-push cut-off until ${MAP_LABELS.asm} confirmed`, chosen: true }]),
      { agent: "pitch", verdict: `built ${pointsFor(p).length} talking points for a ${p.type.toLowerCase()} in ${p.language}, ${p.tone.toLowerCase()} tone` },
      { agent: "huddle", verdict: p.news?.some((n) => n.agent === "huddle") ? "added a newer signal after generation" : "had no conflicting signal for this outlet" },
    ],
    why: `${p.outlet} is on ${p.se}'s beat in ${p.territory}, so the pitch goes to the SFA app automatically. Nobody sends it by hand.`,
    outcome: p.status === "queued" ? `Queued for the next Create pitches batch` : `In ${p.se}'s SFA app since ${p.sfaAt}`,
    link: "View in Pitch",
  };
}

export function coveredTrace(p: Pitch, t: TalkingPoint): ActionTrace {
  const c = t.covered!;
  return {
    input: { label: `Visit by ${c.by}`, detail: `${c.at} · talking point ${t.n}, ${t.topic}`, at: c.when },
    evaluated: [
      { agent: "pitch", verdict: "matched the officer's last recorded visit to this pitch", chosen: true },
      ...(t.fromPlan ? [{ agent: "map" as AgentId, verdict: `counted it against plan initiative #${t.fromPlan}` }] : []),
    ],
    why: `The workbook records each outlet's last SO visit (date and time). A visit on or after the plan date covers the plan's talking point.`,
    outcome: c.note ? `Covered · “${c.note}”` : "Covered on the visit",
    link: "View visit in SFA",
  };
}

/** Plan initiatives a pitch was pushed from, for its header. */
export function sourceLabel(s: PitchSource) {
  if (s.kind === "thermometer") return { text: s.label, mode: "From Thermometer" };
  const i = SEP_INITIATIVES.find((x) => x.id === s.initiative)!;
  return { text: `${SEP_PLAN.label.split(" ")[0]} plan · #${i.n} ${i.title}`, mode: s.mode === "auto" ? `Auto-pushed · ${i.priority}` : `Pushed by ${MAP_LABELS.asm}`, priority: i.priority as Priority };
}

// ---------------------------------------------------------------------------
// Ad hoc pitch (secondary path)
// ---------------------------------------------------------------------------

/** The main officer's three outlets with the oldest visit, first on today's route. */
export const TODAYS_ROUTE = P<string[]>("TODAYS_ROUTE");
export const ADHOC_TOPICS = ["Company introduction", "Outstanding", "New product", "Sell top seller", "Target", "Loyalty", "Maintain & grow", "Open issues", "Upsell / competition"];
export const LANGUAGES = Array.from(new Set([LANGUAGE, "Hindi", "English"]));
export const TONES = ["Balanced", "New-product push", "Collection first", "Relationship"];
